apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: teamfinder
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://hmhardik5021_db_user:KK1Q1L4tpf6D0X6l@cluster0.87ibbde.mongodb.net/?appName=Cluster0"
  JWT_ACCESS_SECRET: "access_secret_prod"
  JWT_REFRESH_SECRET: "refresh_secret_prod"
